name: Commitlint

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Lint PR commits (npx)
        run: |
          BASE_SHA=$(jq -r .pull_request.base.sha "$GITHUB_EVENT_PATH")
          HEAD_SHA=$(jq -r .pull_request.head.sha "$GITHUB_EVENT_PATH")
          npx --yes -p @commitlint/cli@19.5.0 -p @commitlint/config-conventional@19.5.0 \
            commitlint --from "$BASE_SHA" --to "$HEAD_SHA" --verbose -x @commitlint/config-conventional

